>#+TITLE:       关于
#+AUTHOR:      ccsheller
#+EMAIL:       ccsheller@gmail.com
#+DATE:        2015-12-27 周日
#+URI:         /about/
#+KEYWORDS:    About,关于
#+TAGS:        <TODO: insert your tags here>
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: About blog

关于本人，没什么好说的。在魔都作代码搬运工。
本博客为什么要用org生成。主要是想把emacs用起来，并不是因为org有什么牛叉的功能。
为什么要把emacs用起来呢。主要是用vim，总是要按esc；同时我想对vim多做一些定制时，
想到vim是特有脚本想想还是算了。
想到emacs是用elisp（lisp的一种方言，更有通用性）配置，决定学习下。这是一个大坑。
emacs快捷键太多，不做配置跟本没法顺畅的使用。本人不太喜欢做定制，配置不是天天做，
很容易忘，当用别人机器时会发现很难使用。用vim时也是用原生功能，极少配置。
但本人想学emacs，又喜欢折腾。决定克服下。吐嘈下，emacs wiki很不好懂（本人愚钝）。
都说org-mode很强大，我也就学了点皮毛。了解到Org可以转换为其它格式，特别是生成
html。这不是可以用来生成博客吗？以前博客是放在vps中的，几年也没写几篇，想想还是
省点钱吧。放到github上应该也够用了。选择了[[https://hexo.io/zh-cn/][hexo]] 来生成
发布，hexo还是很好用的。为什么不用Jekyll，我现在不想学Ruby，以后也不太可能学。同
时我想学下JavaScript（虽然到现在都没学什么，想学的东西太多）。
说回org生成html，了解到这篇[[http://dayigu.github.io/WhyUseOrgModeToWriteBlog.html][为什么用 org-mode 写 blog？]]，但是他没具体给出评论怎么
加，对于愚钝的我还是算了。又了解到[[https://github.com/kelvinh/org-page][org-page]]， 这个看来很靠谱，可以尝试。然后各种
装，有的插件不好装（有插件的版本不支持新的emacs了），经过前后断断续续两周，认为
配置应该可以了，哪想就是不能生成。各种检查，比对配置，崩溃，看来还是找找简单的方法，于是找到了[[https://lotabout.github.io/orgwiki/how_wiki_is_built.html][本站是
如何搭建的]]，这个好像可行，简单配置，也参考了[[http://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html][Publishing Org-mode files to HTML]]，
终于生成了，但是我想实现默认显示评论（本来就没评论，要读者去点下的体验不好；当然
默认显示评论，拖慢速度的体验也不好），改了下，没成功。查文档应该好改，但是我不甘
心没用上org-page，花了这么多时间。
看了下org-page源码，原来它[[https://github.com/kelvinh/org-page/issues/157][找不到git]]， 不给提示，改了系统环境变量可以找到了。想想
应该可以了，结果还是不能生成（崩溃），再看看代码。原来[[https://github.com/kelvinh/org-page/issues/158][它只生成提交过的文件]]， 想想
这也很合理，但是hexo不是这样的呀。
现在终于可以用org写博客了，说了都是泪。
